version: '3.4'

services:
  bds:
    image: vogles/minecraft-bedrock-server
    environment:
      EULA: "true"
      VERSION: "latest"
    ports:
      - 19132:19132
      - 19133:19133
    volumes:
      - ./bds/backups:/minecraft/server/backups
      - ./bds/config:/minecraft/server/config
      - ./bds/worlds:/minecraft/server/worlds
